// 获取游戏主窗口
// ============================================================================
#include "runtime/modules/runtime_feature_ui_skill_window_runtime_core.inl"
#include "runtime/modules/runtime_feature_runtime_hook_state.inl"
#include "runtime/modules/runtime_feature_mounted_flight_and_ability_state.inl"
#include "runtime/modules/runtime_feature_surface_and_ability_red_runtime.inl"
#include "runtime/modules/runtime_feature_status_bar_buff_slot_runtime.inl"
#include "runtime/modules/runtime_feature_runtime_patch_and_packet_runtime.inl"
#include "runtime/modules/runtime_feature_mounted_double_jump_runtime_core.inl"
#include "runtime/modules/runtime_feature_mount_movement_runtime_core.inl"
#include "runtime/modules/runtime_feature_mounted_double_jump_runtime_handlers.inl"
#include "runtime/modules/runtime_feature_skill_effect_and_release_runtime.inl"
#include "runtime/modules/runtime_feature_ui_overlay_runtime.inl"
#include "runtime/modules/runtime_feature_packet_and_local_setup.inl"
#include "runtime/modules/runtime_feature_ability_red_local_setup.inl"
#include "runtime/modules/runtime_feature_native_hook_setup.inl"
#include "runtime/modules/runtime_feature_deferred_interaction_hooks.inl"
// ============================================================================
#undef kEnableMountedDoubleJumpRuntimeHooks
#undef kEnableMountMovementAbilityRedHooks
#undef kEnableGlobalMovementSetterProtectionHooks
#undef kEnableMountMovementCapPatches
#undef kEnableMountMovementObservationHooks
#undef kEnableMountedFlightPhysicsSpeedHooks
#undef kEnableGlobalMovementOutputClampHook
